### PR TITLE
Centralize all allocations

### PR DESCRIPTION
**Pull request by mingodad**

### CODE REVIEW

**Comment by mingodad** [comment]
Still missing the `free` calls and there is segfaults when trying to execute `./tastwalk` without arguments, I'm looking at it now.

**Comment by mingodad** [comment]
The `tests/taskwalk.c` do not check properly for executing it without arguments.

**Comment by mingodad** [comment]
The `./tgraph` without arguments also segfault and seems due to bad memory allocation.

**Comment by mingodad** [comment]
Executing the generated executables under valgrind shows several memory problems.

**Comment by dibyendumajumdar** [comment]
Thank you for the contribution!

**Pull request merged**
